package main

import (
	"log"
	"net/http"
	"os"
	"path/filepath"

	"fourinrow/analytics"
	"fourinrow/db"
	"fourinrow/server"
)

// spaHandler serves the index.html for any unknown route to support React Router (SPA)
type spaHandler struct {
	staticPath string
	indexPath  string
}

func (h spaHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// join the static path with the requested URL path
	// e.g. "./client/dist" + "/assets/index.js"
	path := filepath.Join(h.staticPath, r.URL.Path)

	// Check if the file exists on disk
	_, err := os.Stat(path)

	// If the file does NOT exist (like /game, /leaderboard), serve index.html
	if os.IsNotExist(err) {
		http.ServeFile(w, r, filepath.Join(h.staticPath, h.indexPath))
		return
	} else if err != nil {
		// If there's a different error (permission etc), return 500
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// If the file DOES exist, serve it normally
	http.FileServer(http.Dir(h.staticPath)).ServeHTTP(w, r)
}

func main() {
	// Initialize database (safe if DATABASE_URL not set)
	db.InitDB()

	// Initialize analytics (stubbed)
	analytics.Producer = analytics.NewStubProducer()

	http.HandleFunc("/ws", server.WebSocketHandler)
	http.HandleFunc("/leaderboard", server.LeaderboardHandler)

	// Serve the "dist" folder generated by 'npm run build'
	spa := spaHandler{staticPath: "./client/dist", indexPath: "index.html"}
	http.Handle("/", spa)

	log.Println("Server running on :5000")
	log.Fatal(http.ListenAndServe(":5000", nil))
}