name: DevSecOps Phase 2 - SCA & DAST

on:
  push:
    branches: [ "main" ]

jobs:
  # ----------------------------------------------------
  # JOB 1: SCA (The Ingredient Inspector)
  # ----------------------------------------------------
  sca-scanning:
    name: Software Composition Analysis (SCA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Trivy will scan your go.mod and package.json for vulnerable third-party libraries
      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
# ----------------------------------------------------
  # JOB 2: DAST (The Automated Hacker)
  # ----------------------------------------------------
  dast-scanning:
    name: Dynamic Analysis (DAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Spin up Kafka and the Game Server
      - name: Build and Start Application
        run: |
          docker compose up -d
          docker build -t fourinrow-app .
          docker run -d -p 5000:5000 -e KAFKA_BROKER=localhost:9092 --network host fourinrow-app
          echo "Waiting for the game, server, and database to boot up..."
          sleep 45 

      # 2. Unlock the folder so ZAP can save its report
      - name: Grant ZAP permission to write report
        run: chmod 777 $GITHUB_WORKSPACE

      # 3. Unleash the automated hacker (OWASP ZAP) against the running app
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000'
          fail_action: false
